name: Publish ModuleSIte on gh-pages

on:
  push:
    branches:
      - deploy-gh-action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          access-token: ${{ secrets.DEPLOY_TOKEN }}
          deploy-branch: deployment-test
          gatsby-args: --prefix-paths
